source('/scratch/nzx3cc/nzx3cc/sbs_paper/scripts/inference.R')

args <- commandArgs(trailingOnly = TRUE)
filename = toString(args[1])
k = as.numeric(args[2])
p = as.numeric(args[3])

rho = as.numeric(args[4])
obs <- unlist(read.table(filename))
sbs = get_mpl_sbs(obs, p, k, rho)
over = get_mpl_over(obs, p, k, rho)
neut = comp_like(obs, nnsfs(k))
print(sbs$value)
print(over$value)
print(neut)
